micronaut:
  application:
    name: micronaut-ecommerce-demo
  server:
    port: 8083

embedjnosql:
  enabled: true
  engine: IN_MEMORY
  data-dir: target/micronaut-data
  auto-flush: true
  flush-interval-ms: 1000
